# ML & AI with LazyPredict

**Authors:** Alexander Michels

The [lazypredict](https://github.com/shankarpandala/lazypredict) Python package is an excellent tool to try out a variety classification and regression methods on a dataset.

We want to work with a specific version of lazypredict, so run the following line of code and after it completes you will want to restart the kernel (Kernel -> Restart). After that, we can skip this cell and proceed with the rest of the notebook.

In [ ]:
# !pip install lazypredict==0.2.16

You may get a `FutureWarning` about pyarrow or dask-expr, you can safely ignore those.

In [2]:
from lazypredict.Supervised import LazyClassifier, LazyRegressor
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

## LazyClassification

This dataset comes from the Diagnostic Wisconsin Breast Cancer Database (https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic). A bit more information on the scikit-learn version: https://scikit-learn.org/stable/datasets/toy_dataset.html#breast-cancer-dataset

In [3]:
breast_cancer_df, classification = load_breast_cancer(return_X_y=True, as_frame=True)
breast_cancer_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.00,0.12,0.28,0.30,0.15,0.24,0.08,...,25.38,17.33,184.60,2019.00,0.16,0.67,0.71,0.27,0.46,0.12
1,20.57,17.77,132.90,1326.00,0.08,0.08,0.09,0.07,0.18,0.06,...,24.99,23.41,158.80,1956.00,0.12,0.19,0.24,0.19,0.28,0.09
2,19.69,21.25,130.00,1203.00,0.11,0.16,0.20,0.13,0.21,0.06,...,23.57,25.53,152.50,1709.00,0.14,0.42,0.45,0.24,0.36,0.09
3,11.42,20.38,77.58,386.10,0.14,0.28,0.24,0.11,0.26,0.10,...,14.91,26.50,98.87,567.70,0.21,0.87,0.69,0.26,0.66,0.17
4,20.29,14.34,135.10,1297.00,0.10,0.13,0.20,0.10,0.18,0.06,...,22.54,16.67,152.20,1575.00,0.14,0.20,0.40,0.16,0.24,0.08

According to the documentation, we are trying to classify these breast masses into either Malignant [harmful or cancerous] (212 cases) or Benign (357 cases).

In [4]:
print(f"The classes in the dataset are: {set(classification)}")
print(f"There are {len(classification)} total observations.")
for cla in set(classification):
    print(f"  * There are {len(classification[classification == cla])} data points equal to {cla}")
classification.head()

The classes in the dataset are: {0, 1}
There are 569 total observations.
  * There are 212 data points equal to 0
  * There are 357 data points equal to 1

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

Here we will re-load the data as arrays that are easier for the ML approach to analyze:

In [5]:
data = load_breast_cancer()
X = data.data
y = data.target

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

You may see an error that says "Click to show javascript error." which can be ignored.

In [7]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

  0%|          | 0/29 [00:00<?, ?it/s]

[LightGBM] [Info] Number of positive: 290, number of negative: 165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4538
[LightGBM] [Info] Number of data points in the train set: 455, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.637363 -> initscore=0.563935
[LightGBM] [Info] Start training from score 0.563935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [8]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
SVC,0.98,0.98,0.98,0.98,0.01
RandomForestClassifier,0.97,0.97,0.97,0.97,0.29
LGBMClassifier,0.97,0.97,0.97,0.97,0.10
LogisticRegression,0.96,0.96,0.96,0.96,0.01
SGDClassifier,0.96,0.96,0.96,0.96,0.05
PassiveAggressiveClassifier,0.96,0.96,0.96,0.96,0.01
AdaBoostClassifier,0.96,0.96,0.96,0.96,0.17
LinearDiscriminantAnalysis,0.96,0.96,0.96,0.96,0.01
CalibratedClassifierCV,0.96,0.96,0.96,0.96,0.03
RidgeClassifierCV,0.96,0.96,0.96,0.96,0.01
RidgeClassifier,0.96,0.96,0.96,0.96,0.01
QuadraticDiscriminantAnalysis,0.96,0.96,0.96,0.96,0.01
XGBClassifier,0.96,0.96,0.96,0.96,0.15
LabelPropagation,0.96,0.95,0.95,0.96,0.02
LabelSpreading,0.96,0.95,0.95,0.96,0.10
BaggingClassifier,0.95,0.95,0.95,0.95,0.07
LinearSVC,0.95,0.95,0.95,0.95,0.08
KNeighborsClassifier,0.96,0.95,0.95,0.96,0.13
ExtraTreesClassifier,0.95,0.94,0.94,0.95,0.10
NuSVC,0.95,0.94,0.94,0.95,0.09
BernoulliNB,0.93,0.94,0.94,0.93,0.01
NearestCentroid,0.93,0.92,0.92,0.93,0.08
DecisionTreeClassifier,0.91,0.92,0.92,0.91,0.02
ExtraTreeClassifier,0.91,0.91,0.91,0.91,0.01
GaussianNB,0.90,0.90,0.90,0.90,0.01
Perceptron,0.87,0.87,0.87,0.87,0.01
DummyClassifier,0.59,0.50,0.50,0.44,0.01

## LazyRegression

LazyPredict also works for regression!

This dataset comes from a 2004 paper that analyzed 442 diabetes patients to explore how ten variables (age, sex, BMI, blood pressure, and six blood serum measurements) explain disease progression after one year. https://scikit-learn.org/stable/datasets/toy_dataset.html#diabetes-dataset

In [14]:
diabetes_df, classification = load_diabetes(return_X_y=True, as_frame=True)
diabetes_df.head()

    age   sex   bmi    bp    s1    s2    s3    s4    s5    s6
0  0.04  0.05  0.06  0.02 -0.04 -0.03 -0.04 -0.00  0.02 -0.02
1 -0.00 -0.04 -0.05 -0.03 -0.01 -0.02  0.07 -0.04 -0.07 -0.09
2  0.09  0.05  0.04 -0.01 -0.05 -0.03 -0.03 -0.00  0.00 -0.03
3 -0.09 -0.04 -0.01 -0.04  0.01  0.02 -0.04  0.03  0.02 -0.01
4  0.01 -0.04 -0.04  0.02  0.00  0.02  0.01 -0.00 -0.03 -0.05

In [15]:
diabetes  = load_diabetes()
X, y = shuffle(diabetes.data, diabetes.target, random_state=0)
X = X.astype(np.float32)

In [16]:
offset = int(X.shape[0] * 0.9) # save the last 10% for testing
print(offset)

397

In [17]:
X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]

You may see an error that says "Click to show javascript error." which can be ignored.

In [18]:
y_train

array([321., 215., 127.,  64., 175., 275., 179., 232., 142.,  99., 252.,
       174., 129.,  74., 264.,  49.,  86.,  75., 101., 155., 170., 276.,
       110., 136.,  68., 128., 103.,  93., 191., 196., 217., 181., 168.,
       200., 219., 281., 151., 257.,  49., 198.,  96., 179.,  95., 198.,
       244.,  89., 214., 182.,  84., 270., 156., 138., 113., 131., 195.,
       171., 122.,  61., 230., 235.,  52., 121., 144., 107., 132., 302.,
        53., 317., 137.,  57.,  98., 170.,  88.,  90.,  67., 163., 104.,
       186., 180., 283., 141., 150.,  47., 297., 104.,  49., 103., 142.,
        59.,  85., 137.,  53.,  51., 197., 135.,  72., 208., 237., 145.,
       110., 292.,  97., 197., 158., 163.,  63., 192., 233.,  68., 160.,
       178.,  68., 109.,  94., 118., 275., 275., 127., 281.,  71.,  42.,
        71., 128., 272., 135.,  51., 220., 167.,  78., 131., 212., 182.,
       174., 259.,  77.,  91., 310.,  84., 134., 102., 128., 306., 245.,
       201., 183., 111.,  96., 125., 182., 177.,  48.,  97., 259., 288.,
       242.,  69.,  31., 154., 150.,  52., 261., 118., 102., 139.,  51.,
        58., 144., 178.,  97.,  78., 129., 258., 124., 198., 185.,  66.,
       237., 178., 275., 268., 242., 200., 214., 246., 236.,  85., 114.,
        93.,  99.,  72., 270., 111.,  83.,  87.,  42., 172.,  65., 259.,
       279., 141., 144., 220.,  90., 101.,  53.,  67.,  72., 121., 303.,
       232., 140., 190., 221.,  71., 116., 111., 280., 233.,  78., 150.,
       283.,  64., 140.,  65., 225., 206.,  63., 296., 173.,  85., 141.,
        50.,  25., 153.,  55., 139., 336.,  73.,  95., 109.,  44., 180.,
       263., 148.,  79.,  65., 102., 220., 277., 246., 200., 262., 191.,
        97., 184.,  85., 248., 150., 268.,  59.,  70.,  88., 100., 190.,
       113.,  66., 243., 185., 262.,  48., 160., 217., 210., 132., 257.,
       104., 126., 292., 166.,  83.,  81., 144., 281.,  72.,  39., 109.,
        60., 258., 178., 168.,  87.,  77., 216., 206., 142., 161., 265.,
        60., 200., 265., 272., 146.,  94.,  55.,  69., 138., 258., 143.,
       172.,  89.,  69., 199.,  55.,  45., 265.,  91., 170.,  55., 202.,
       155.,  77.,  77.,  71., 123.,  84., 252.,  52.,  40., 274., 143.,
       245.,  92., 151.,  39., 235.,  92., 253.,  94.,  81., 346.,  90.,
       181., 162., 277., 152., 178., 124.,  75., 263., 202., 200., 108.,
        96.,  60.,  72., 107.,  54., 158., 152., 220., 308., 249., 222.,
        65., 173.,  88.,  72., 164.,  52., 115., 200.,  90., 248.,  37.,
       230.,  63., 273.,  61.,  53., 189., 241., 118., 252., 104., 219.,
       115., 332., 131., 185.,  63., 131.,  88., 187., 196.,  59., 341.,
       109.])

In [19]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

  0%|          | 0/42 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 642
[LightGBM] [Info] Number of data points in the train set: 397, number of used features: 10
[LightGBM] [Info] Start training from score 151.959698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [20]:
models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
SGDRegressor,0.41,0.55,55.75,0.01
Lasso,0.41,0.54,55.87,0.08
LassoLars,0.41,0.54,55.87,0.01
LarsCV,0.41,0.54,55.95,0.01
BayesianRidge,0.41,0.54,55.97,0.01
LassoLarsIC,0.41,0.54,55.99,0.01
ElasticNetCV,0.41,0.54,56.01,0.06
RidgeCV,0.40,0.54,56.19,0.01
Ridge,0.40,0.54,56.19,0.01
LassoCV,0.40,0.54,56.23,0.14
HuberRegressor,0.40,0.54,56.26,0.01
LinearRegression,0.40,0.53,56.41,0.01
TransformedTargetRegressor,0.40,0.53,56.41,0.01
Lars,0.40,0.53,56.41,0.01
LassoLarsCV,0.40,0.53,56.41,0.02
PassiveAggressiveRegressor,0.39,0.53,56.55,0.01
PoissonRegressor,0.39,0.53,56.94,0.01
OrthogonalMatchingPursuitCV,0.38,0.52,57.10,0.08
ElasticNet,0.34,0.49,59.03,0.01
ExtraTreesRegressor,0.31,0.46,60.49,0.14
GammaRegressor,0.30,0.46,60.90,0.01
TweedieRegressor,0.29,0.45,61.30,0.01
KNeighborsRegressor,0.27,0.43,62.22,0.01
LinearSVR,0.26,0.43,62.32,0.01
GradientBoostingRegressor,0.26,0.43,62.51,0.28
LGBMRegressor,0.26,0.43,62.60,0.06
HistGradientBoostingRegressor,0.24,0.42,63.21,0.09
AdaBoostRegressor,0.20,0.38,65.16,0.09
RandomForestRegressor,0.18,0.36,65.88,0.25
OrthogonalMatchingPursuit,0.08,0.29,69.61,0.01
XGBRegressor,0.08,0.29,69.83,0.10
RANSACRegressor,0.06,0.28,70.33,0.07
BaggingRegressor,-0.06,0.18,74.69,0.04
SVR,-0.06,0.18,74.85,0.01
NuSVR,-0.07,0.17,75.13,0.01
DummyRegressor,-0.29,-0.00,82.67,0.01
QuantileRegressor,-0.32,-0.02,83.62,0.03
DecisionTreeRegressor,-0.66,-0.28,93.60,0.01
GaussianProcessRegressor,-0.78,-0.37,96.85,0.05
ExtraTreeRegressor,-0.90,-0.47,100.12,0.01
MLPRegressor,-1.06,-0.59,104.33,0.81
KernelRidge,-3.90,-2.78,160.80,0.10

## Regression with your own Dataset!

Find a dataset of your own and let's test LazyPredict on it! First, you will want to upload the data to this JupyterHub using the "Upload Files" (line with an arrow pointing up) button in the File Browser side menu.

We will assume you are uploading a CSV file. To load the CSV, we can use the pandas `read_csv` function.

**For the following cells, you will need to change file names and variables names!**

In [ ]:
# load the csv file and save it as a variable "mydf" 
mydf = pd.read_csv("NAME OF YOUR FILE GOES HERE")
print(len(mydf))  # print the number of rows
mydf.head()  # examine the data to ensure it loaded properly

You may have some data cleaning to do! For example, you may want to check for "NaN" (not a number) values. You may also want to check the documentation for the data you are using because other numbers like `-1` or `-999` maybe be used as `nan`.

As an example, the following code will filter out any rows with a -999. However, you will have to figure out what "nan" or missing data flags exist in your own data.

In [ ]:
mydf = mydf.replace(-999.00, np.nan)  # replace all of the -999 with nans
mydf = mydf.dropna()  # drop any rows with a nan
print(len(mydf))
mydf.head()

Now, you need to figure out what your input variables will be and what value you are trying to predict. Think about which variables may be useful for predicting.

If you uploaded a CSV, you may have an "Unnamed: 0" column that can be dropped. Other variables like a "FIPS" code for a spatial unit are useful for identifying the data but shouldn't be used as a predictor of your output variable.

**The variables below are examples from the CDC SVI, be sure to use the appropriate variables for your dataset and task!**

In [ ]:
x = mydf[["EP_NOHSDP", "EP_AGE65", "EP_AGE17", "EP_DISABL", "EP_SNGPNT", "EP_MINRTY"]].to_numpy()  # get the variables we want as a numpy array
y = mydf["EP_POV150"].to_numpy()

In [ ]:
x

In [ ]:
y

The following cells are the same as above:
* Calculate an offset so we can save some data for testing.
* Slice our data into training and testing.
* Create our LazyRegressor object and fit the models.
* Show the performance metrics.

In [ ]:
offset = int(x.shape[0] * 0.9) # save the last 10% for testing
print(offset)

In [ ]:
X_train, y_train = x[:offset], y[:offset]
X_test, y_test = x[offset:], y[offset:]

You may see an error that says "Click to show javascript error." which can be ignored.

If some models fail, don't worry too much. You can always make adjustments later!

In [ ]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

In [ ]:
models